# Generated by Django 3.2.9 on 2021-12-30 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20211222_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_lines', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тэги')),
                ('about_me', models.CharField(blank=True, max_length=512, null=True, verbose_name='Обо мне')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'N')], default='N', max_length=1, verbose_name='Пол')),
                ('github_profile', models.URLField(blank=True, null=True, verbose_name='Github')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
